name: Deploy to GitHub Pages

on:
    push:
        branches: ['mainline']

env:
    CI: false

jobs:
    build:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        permissions:
            contents: 'read'
            id-token: 'write'
            pages: 'write'
            actions: 'write'
            checks: 'write'
            deployments: 'write'
        strategy:
            matrix:
                node-version: [21.x]

        steps:
            - uses: actions/checkout@v4

            - name: Fetch blog posts
              run: |
                  curl https://aswinrajeev.medium.com/feed -o aswin-home/public/blog-feed.rss
                  cat aswin-home/public/blog-feed.rss

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Build
              run: |
                  cd aswin-home
                  npm install
                  npm run build
                  
            - name: Check for hard links
              run: |
                cd aswin-home/out
                find . -type f -links +1

            - name: Remove symlinks and problematic files
              run: |
                  cd aswin-home/out
                  find . -type l -delete
                  find . -type d -name '.next' -exec rm -rf {} + 2>/dev/null || true
                  find . -name '.DS_Store' -delete

            - name: Setup Pages
              uses: actions/configure-pages@v4
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: github-pages
                  path: 'aswin-home/out/'
                  retention-days: 1
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
